### ISSUE TITLE
Please, consider publishing the latest versions to pub.

### ISSUE THREAD

**Issue by ariedov** [pulyaevskiy/firebase-functions-interop#41]
Right now the pub link leads to an old version which is not compatible with Dart 2.0. Is it possible to update the latest version to the `pub`, so the page there will be more attractive/consistent?

**Comment by pulyaevskiy** [comment]
I've been thinking about this for a while now. The issue is that to fix this I need to publish a stable version to Pub, but I was hesitant to do this before as I wasn't sure about quality and completeness.

As of now, I'm less concerned about quality and bugs as it seems like enough people have been using this package (including myself). It's still not feature complete but that's not a strict blocker for releasing stable version.

One thing I'd like to do before releasing  this package as stable is to release all `node_interop` packages as stable as well, as these are direct dependencies.

P.S.: Of course I shouldn't have published old versions of this package as stable to start with, but it is what it is now.

**Comment by ariedov** [comment]
The main issue is that I'd never know there is a Dart 2.0 compatible version. Clicking on the `module page` link was almost an accident.

**Comment by jasonbray** [comment]
Are there issues we can tackle that would help you feel more comfortable with quality/completeness?

**Comment by pulyaevskiy** [comment]
Thanks everyone for your input. Just an FYI I'm getting closer here and published following required dependencies as stable:

* `node_interop` (1.0.0)
* `firebase_admin_interop` (already 1.1.0 which is upgraded to latest JS SDK 6.2.0)

This package is the last one, so should get it done this week.

**Comment by pulyaevskiy** [comment]
Ok, finally 1.0.0 is out: https://pub.dartlang.org/packages/firebase_functions_interop

Note that this release includes a breaking change so make sure to checkout CHANGELOG.md

Thanks everyone for your support!
